<?php

return [
    0 => [
        'ns' => 6,
        'title' => 'Файл:С. Г. Чириков - Александр Сергеевич Пушкин (акварель).jpg',
        'missing' => true,
        'known' => true,
        'imagerepository' => 'shared',
        'imageinfo' => [
            0 => [
                'thumburl' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/%D0%A1._%D0%93._%D0%A7%D0%B8%D1%80%D0%B8%D0%BA%D0%BE%D0%B2_-_%D0%90%D0%BB%D0%B5%D0%BA%D1%81%D0%B0%D0%BD%D0%B4%D1%80_%D0%A1%D0%B5%D1%80%D0%B3%D0%B5%D0%B5%D0%B2%D0%B8%D1%87_%D0%9F%D1%83%D1%88%D0%BA%D0%B8%D0%BD_%28%D0%B0%D0%BA%D0%B2%D0%B0%D1%80%D0%B5%D0%BB%D1%8C%29.jpg/227px-%D0%A1._%D0%93._%D0%A7%D0%B8%D1%80%D0%B8%D0%BA%D0%BE%D0%B2_-_%D0%90%D0%BB%D0%B5%D0%BA%D1%81%D0%B0%D0%BD%D0%B4%D1%80_%D0%A1%D0%B5%D1%80%D0%B3%D0%B5%D0%B5%D0%B2%D0%B8%D1%87_%D0%9F%D1%83%D1%88%D0%BA%D0%B8%D0%BD_%28%D0%B0%D0%BA%D0%B2%D0%B0%D1%80%D0%B5%D0%BB%D1%8C%29.jpg',
                'thumbwidth' => 227,
                'thumbheight' => 300,
                'url' => 'https://upload.wikimedia.org/wikipedia/commons/8/8c/%D0%A1._%D0%93._%D0%A7%D0%B8%D1%80%D0%B8%D0%BA%D0%BE%D0%B2_-_%D0%90%D0%BB%D0%B5%D0%BA%D1%81%D0%B0%D0%BD%D0%B4%D1%80_%D0%A1%D0%B5%D1%80%D0%B3%D0%B5%D0%B5%D0%B2%D0%B8%D1%87_%D0%9F%D1%83%D1%88%D0%BA%D0%B8%D0%BD_%28%D0%B0%D0%BA%D0%B2%D0%B0%D1%80%D0%B5%D0%BB%D1%8C%29.jpg',
                'descriptionurl' => 'https://commons.wikimedia.org/wiki/File:%D0%A1._%D0%93._%D0%A7%D0%B8%D1%80%D0%B8%D0%BA%D0%BE%D0%B2_-_%D0%90%D0%BB%D0%B5%D0%BA%D1%81%D0%B0%D0%BD%D0%B4%D1%80_%D0%A1%D0%B5%D1%80%D0%B3%D0%B5%D0%B5%D0%B2%D0%B8%D1%87_%D0%9F%D1%83%D1%88%D0%BA%D0%B8%D0%BD_(%D0%B0%D0%BA%D0%B2%D0%B0%D1%80%D0%B5%D0%BB%D1%8C).jpg',
                'descriptionshorturl' => 'https://commons.wikimedia.org/w/index.php?curid=3181543',
                'mime' => 'image/jpeg',
            ],
        ],
    ],
    1 => [
        'ns' => 6,
        'title' => 'Файл:Родословное дерево Пушкиных.jpg',
        'missing' => true,
        'known' => true,
        'imagerepository' => 'shared',
        'imageinfo' => [
            0 => [
                'thumburl' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/%D0%A0%D0%BE%D0%B4%D0%BE%D1%81%D0%BB%D0%BE%D0%B2%D0%BD%D0%BE%D0%B5_%D0%B4%D0%B5%D1%80%D0%B5%D0%B2%D0%BE_%D0%9F%D1%83%D1%88%D0%BA%D0%B8%D0%BD%D1%8B%D1%85.jpg/193px-%D0%A0%D0%BE%D0%B4%D0%BE%D1%81%D0%BB%D0%BE%D0%B2%D0%BD%D0%BE%D0%B5_%D0%B4%D0%B5%D1%80%D0%B5%D0%B2%D0%BE_%D0%9F%D1%83%D1%88%D0%BA%D0%B8%D0%BD%D1%8B%D1%85.jpg',
                'thumbwidth' => 193,
                'thumbheight' => 300,
                'url' => 'https://upload.wikimedia.org/wikipedia/commons/2/21/%D0%A0%D0%BE%D0%B4%D0%BE%D1%81%D0%BB%D0%BE%D0%B2%D0%BD%D0%BE%D0%B5_%D0%B4%D0%B5%D1%80%D0%B5%D0%B2%D0%BE_%D0%9F%D1%83%D1%88%D0%BA%D0%B8%D0%BD%D1%8B%D1%85.jpg',
                'descriptionurl' => 'https://commons.wikimedia.org/wiki/File:%D0%A0%D0%BE%D0%B4%D0%BE%D1%81%D0%BB%D0%BE%D0%B2%D0%BD%D0%BE%D0%B5_%D0%B4%D0%B5%D1%80%D0%B5%D0%B2%D0%BE_%D0%9F%D1%83%D1%88%D0%BA%D0%B8%D0%BD%D1%8B%D1%85.jpg',
                'descriptionshorturl' => 'https://commons.wikimedia.org/w/index.php?curid=3181587',
                'mime' => 'image/jpeg',
            ],
        ],
    ],
    2 => [
        'ns' => 6,
        'title' => 'Файл:Дом на Немецкой улице (Бауманская, д. 57 б), где родился А. С. Пушкин, как считалось до революции.JPG',
        'missing' => true,
        'known' => true,
        'imagerepository' => 'shared',
        'imageinfo' => [
            0 => [
                'thumburl' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/%D0%94%D0%BE%D0%BC_%D0%BD%D0%B0_%D0%9D%D0%B5%D0%BC%D0%B5%D1%86%D0%BA%D0%BE%D0%B9_%D1%83%D0%BB%D0%B8%D1%86%D0%B5_%28%D0%91%D0%B0%D1%83%D0%BC%D0%B0%D0%BD%D1%81%D0%BA%D0%B0%D1%8F%2C_%D0%B4._57_%D0%B1%29%2C_%D0%B3%D0%B4%D0%B5_%D1%80%D0%BE%D0%B4%D0%B8%D0%BB%D1%81%D1%8F_%D0%90._%D0%A1._%D0%9F%D1%83%D1%88%D0%BA%D0%B8%D0%BD%2C_%D0%BA%D0%B0%D0%BA_%D1%81%D1%87%D0%B8%D1%82%D0%B0%D0%BB%D0%BE%D1%81%D1%8C_%D0%B4%D0%BE_%D1%80%D0%B5%D0%B2%D0%BE%D0%BB%D1%8E%D1%86%D0%B8%D0%B8.JPG/300px-thumbnail.jpg',
                'thumbwidth' => 300,
                'thumbheight' => 211,
                'url' => 'https://upload.wikimedia.org/wikipedia/commons/8/8a/%D0%94%D0%BE%D0%BC_%D0%BD%D0%B0_%D0%9D%D0%B5%D0%BC%D0%B5%D1%86%D0%BA%D0%BE%D0%B9_%D1%83%D0%BB%D0%B8%D1%86%D0%B5_%28%D0%91%D0%B0%D1%83%D0%BC%D0%B0%D0%BD%D1%81%D0%BA%D0%B0%D1%8F%2C_%D0%B4._57_%D0%B1%29%2C_%D0%B3%D0%B4%D0%B5_%D1%80%D0%BE%D0%B4%D0%B8%D0%BB%D1%81%D1%8F_%D0%90._%D0%A1._%D0%9F%D1%83%D1%88%D0%BA%D0%B8%D0%BD%2C_%D0%BA%D0%B0%D0%BA_%D1%81%D1%87%D0%B8%D1%82%D0%B0%D0%BB%D0%BE%D1%81%D1%8C_%D0%B4%D0%BE_%D1%80%D0%B5%D0%B2%D0%BE%D0%BB%D1%8E%D1%86%D0%B8%D0%B8.JPG',
                'descriptionurl' => 'https://commons.wikimedia.org/wiki/File:%D0%94%D0%BE%D0%BC_%D0%BD%D0%B0_%D0%9D%D0%B5%D0%BC%D0%B5%D1%86%D0%BA%D0%BE%D0%B9_%D1%83%D0%BB%D0%B8%D1%86%D0%B5_(%D0%91%D0%B0%D1%83%D0%BC%D0%B0%D0%BD%D1%81%D0%BA%D0%B0%D1%8F,_%D0%B4._57_%D0%B1),_%D0%B3%D0%B4%D0%B5_%D1%80%D0%BE%D0%B4%D0%B8%D0%BB%D1%81%D1%8F_%D0%90._%D0%A1._%D0%9F%D1%83%D1%88%D0%BA%D0%B8%D0%BD,_%D0%BA%D0%B0%D0%BA_%D1%81%D1%87%D0%B8%D1%82%D0%B0%D0%BB%D0%BE%D1%81%D1%8C_%D0%B4%D0%BE_%D1%80%D0%B5%D0%B2%D0%BE%D0%BB%D1%8E%D1%86%D0%B8%D0%B8.JPG',
                'descriptionshorturl' => 'https://commons.wikimedia.org/w/index.php?curid=12692237',
                'mime' => 'image/jpeg',
            ],
        ],
    ],
    3 => [
        'ns' => 6,
        'title' => 'Файл:Wikisource-logo.svg',
        'missing' => true,
        'known' => true,
        'imagerepository' => 'shared',
        'imageinfo' => [
            0 => [
                'thumburl' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Wikisource-logo.svg/286px-Wikisource-logo.svg.png',
                'thumbwidth' => 286,
                'thumbheight' => 300,
                'url' => 'https://upload.wikimedia.org/wikipedia/commons/4/4c/Wikisource-logo.svg',
                'descriptionurl' => 'https://commons.wikimedia.org/wiki/File:Wikisource-logo.svg',
                'descriptionshorturl' => 'https://commons.wikimedia.org/w/index.php?curid=838446',
                'mime' => 'image/svg+xml',
            ],
        ],
    ],
    4 => [
        'ns' => 6,
        'title' => 'Файл:Wikiquote-logo.svg',
        'missing' => true,
        'known' => true,
        'imagerepository' => 'shared',
        'imageinfo' => [
            0 => [
                'thumburl' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Wikiquote-logo.svg/253px-Wikiquote-logo.svg.png',
                'thumbwidth' => 253,
                'thumbheight' => 300,
                'url' => 'https://upload.wikimedia.org/wikipedia/commons/f/fa/Wikiquote-logo.svg',
                'descriptionurl' => 'https://commons.wikimedia.org/wiki/File:Wikiquote-logo.svg',
                'descriptionshorturl' => 'https://commons.wikimedia.org/w/index.php?curid=2922874',
                'mime' => 'image/svg+xml',
            ],
        ],
    ],
    5 => [
        'ns' => 6,
        'title' => 'Файл:Wikipedia interwiki section gear icon.svg',
        'missing' => true,
        'known' => true,
        'imagerepository' => 'shared',
        'imageinfo' => [
            0 => [
                'thumburl' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/Wikipedia_interwiki_section_gear_icon.svg/300px-Wikipedia_interwiki_section_gear_icon.svg.png',
                'thumbwidth' => 300,
                'thumbheight' => 300,
                'url' => 'https://upload.wikimedia.org/wikipedia/commons/c/c9/Wikipedia_interwiki_section_gear_icon.svg',
                'descriptionurl' => 'https://commons.wikimedia.org/wiki/File:Wikipedia_interwiki_section_gear_icon.svg',
                'descriptionshorturl' => 'https://commons.wikimedia.org/w/index.php?curid=49699534',
                'mime' => 'image/svg+xml',
            ],
        ],
    ],
    6 => [
        'ns' => 6,
        'title' => 'Файл:Wikinews-logo.svg',
        'missing' => true,
        'known' => true,
        'imagerepository' => 'shared',
        'imageinfo' => [
            0 => [
                'thumburl' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/Wikinews-logo.svg/300px-Wikinews-logo.svg.png',
                'thumbwidth' => 300,
                'thumbheight' => 164,
                'url' => 'https://upload.wikimedia.org/wikipedia/commons/2/24/Wikinews-logo.svg',
                'descriptionurl' => 'https://commons.wikimedia.org/wiki/File:Wikinews-logo.svg',
                'descriptionshorturl' => 'https://commons.wikimedia.org/w/index.php?curid=1023995',
                'mime' => 'image/svg+xml',
            ],
        ],
    ],
    7 => [
        'ns' => 6,
        'title' => 'Файл:Sovremennik.jpg',
        'missing' => true,
        'known' => true,
        'imagerepository' => 'shared',
        'imageinfo' => [
            0 => [
                'thumburl' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Sovremennik.jpg/190px-Sovremennik.jpg',
                'thumbwidth' => 190,
                'thumbheight' => 300,
                'url' => 'https://upload.wikimedia.org/wikipedia/commons/a/a2/Sovremennik.jpg',
                'descriptionurl' => 'https://commons.wikimedia.org/wiki/File:Sovremennik.jpg',
                'descriptionshorturl' => 'https://commons.wikimedia.org/w/index.php?curid=1071945',
                'mime' => 'image/jpeg',
            ],
        ],
    ],
    8 => [
        'ns' => 6,
        'title' => 'Файл:Pushkinwriting.jpg',
        'missing' => true,
        'known' => true,
        'imagerepository' => 'shared',
        'imageinfo' => [
            0 => [
                'thumburl' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/Pushkinwriting.jpg/300px-Pushkinwriting.jpg',
                'thumbwidth' => 300,
                'thumbheight' => 225,
                'url' => 'https://upload.wikimedia.org/wikipedia/commons/c/cc/Pushkinwriting.jpg',
                'descriptionurl' => 'https://commons.wikimedia.org/wiki/File:Pushkinwriting.jpg',
                'descriptionshorturl' => 'https://commons.wikimedia.org/w/index.php?curid=37272212',
                'mime' => 'image/jpeg',
            ],
        ],
    ],
    9 => [
        'ns' => 6,
        'title' => 'Файл:Pushkin farewell to the sea.jpg',
        'missing' => true,
        'known' => true,
        'imagerepository' => 'shared',
        'imageinfo' => [
            0 => [
                'thumburl' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/86/Pushkin_farewell_to_the_sea.jpg/206px-Pushkin_farewell_to_the_sea.jpg',
                'thumbwidth' => 206,
                'thumbheight' => 300,
                'url' => 'https://upload.wikimedia.org/wikipedia/commons/8/86/Pushkin_farewell_to_the_sea.jpg',
                'descriptionurl' => 'https://commons.wikimedia.org/wiki/File:Pushkin_farewell_to_the_sea.jpg',
                'descriptionshorturl' => 'https://commons.wikimedia.org/w/index.php?curid=3824636',
                'mime' => 'image/jpeg',
            ],
        ],
    ],
    10 => [
        'ns' => 6,
        'title' => 'Файл:Pushkin derzhavin.jpg',
        'missing' => true,
        'known' => true,
        'imagerepository' => 'shared',
        'imageinfo' => [
            0 => [
                'thumburl' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8b/Pushkin_derzhavin.jpg/300px-Pushkin_derzhavin.jpg',
                'thumbwidth' => 300,
                'thumbheight' => 195,
                'url' => 'https://upload.wikimedia.org/wikipedia/commons/8/8b/Pushkin_derzhavin.jpg',
                'descriptionurl' => 'https://commons.wikimedia.org/wiki/File:Pushkin_derzhavin.jpg',
                'descriptionshorturl' => 'https://commons.wikimedia.org/w/index.php?curid=551048',
                'mime' => 'image/jpeg',
            ],
        ],
    ],
    11 => [
        'ns' => 6,
        'title' => 'Файл:Pushkin Signature.svg',
        'missing' => true,
        'known' => true,
        'imagerepository' => 'shared',
        'imageinfo' => [
            0 => [
                'thumburl' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Pushkin_Signature.svg/300px-Pushkin_Signature.svg.png',
                'thumbwidth' => 300,
                'thumbheight' => 88,
                'url' => 'https://upload.wikimedia.org/wikipedia/commons/4/45/Pushkin_Signature.svg',
                'descriptionurl' => 'https://commons.wikimedia.org/wiki/File:Pushkin_Signature.svg',
                'descriptionshorturl' => 'https://commons.wikimedia.org/w/index.php?curid=8882894',
                'mime' => 'image/svg+xml',
            ],
        ],
    ],
    12 => [
        'ns' => 6,
        'title' => 'Файл:Pushkin Sergey L.jpg',
        'missing' => true,
        'known' => true,
        'imagerepository' => 'shared',
        'imageinfo' => [
            0 => [
                'thumburl' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Pushkin_Sergey_L.jpg/240px-Pushkin_Sergey_L.jpg',
                'thumbwidth' => 240,
                'thumbheight' => 300,
                'url' => 'https://upload.wikimedia.org/wikipedia/commons/2/2e/Pushkin_Sergey_L.jpg',
                'descriptionurl' => 'https://commons.wikimedia.org/wiki/File:Pushkin_Sergey_L.jpg',
                'descriptionshorturl' => 'https://commons.wikimedia.org/w/index.php?curid=11641570',
                'mime' => 'image/jpeg',
            ],
        ],
    ],
    13 => [
        'ns' => 6,
        'title' => 'Файл:Pushkin Selfportrait with Onegin.jpg',
        'missing' => true,
        'known' => true,
        'imagerepository' => 'shared',
        'imageinfo' => [
            0 => [
                'thumburl' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Pushkin_Selfportrait_with_Onegin.jpg/223px-Pushkin_Selfportrait_with_Onegin.jpg',
                'thumbwidth' => 223,
                'thumbheight' => 300,
                'url' => 'https://upload.wikimedia.org/wikipedia/commons/e/e0/Pushkin_Selfportrait_with_Onegin.jpg',
                'descriptionurl' => 'https://commons.wikimedia.org/wiki/File:Pushkin_Selfportrait_with_Onegin.jpg',
                'descriptionshorturl' => 'https://commons.wikimedia.org/w/index.php?curid=1734369',
                'mime' => 'image/jpeg',
            ],
        ],
    ],
    14 => [
        'ns' => 6,
        'title' => 'Файл:Pushkin MuseumP1060648.jpg',
        'missing' => true,
        'known' => true,
        'imagerepository' => 'shared',
        'imageinfo' => [
            0 => [
                'thumburl' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Pushkin_MuseumP1060648.jpg/207px-Pushkin_MuseumP1060648.jpg',
                'thumbwidth' => 207,
                'thumbheight' => 300,
                'url' => 'https://upload.wikimedia.org/wikipedia/commons/0/0b/Pushkin_MuseumP1060648.jpg',
                'descriptionurl' => 'https://commons.wikimedia.org/wiki/File:Pushkin_MuseumP1060648.jpg',
                'descriptionshorturl' => 'https://commons.wikimedia.org/w/index.php?curid=10182479',
                'mime' => 'image/jpeg',
            ],
        ],
    ],
    15 => [
        'ns' => 6,
        'title' => 'Файл:Pushkin Alexander self portret, 1829.jpg',
        'missing' => true,
        'known' => true,
        'imagerepository' => 'shared',
        'imageinfo' => [
            0 => [
                'thumburl' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Pushkin_Alexander_self_portret%2C_1829.jpg/300px-Pushkin_Alexander_self_portret%2C_1829.jpg',
                'thumbwidth' => 300,
                'thumbheight' => 289,
                'url' => 'https://upload.wikimedia.org/wikipedia/commons/3/38/Pushkin_Alexander_self_portret%2C_1829.jpg',
                'descriptionurl' => 'https://commons.wikimedia.org/wiki/File:Pushkin_Alexander_self_portret,_1829.jpg',
                'descriptionshorturl' => 'https://commons.wikimedia.org/w/index.php?curid=3753212',
                'mime' => 'image/jpeg',
            ],
        ],
    ],
    16 => [
        'ns' => 6,
        'title' => 'Файл:Pushkin Alexander by Sokolov P..jpg',
        'missing' => true,
        'known' => true,
        'imagerepository' => 'shared',
        'imageinfo' => [
            0 => [
                'thumburl' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Pushkin_Alexander_by_Sokolov_P..jpg/232px-Pushkin_Alexander_by_Sokolov_P..jpg',
                'thumbwidth' => 232,
                'thumbheight' => 300,
                'url' => 'https://upload.wikimedia.org/wikipedia/commons/c/cb/Pushkin_Alexander_by_Sokolov_P..jpg',
                'descriptionurl' => 'https://commons.wikimedia.org/wiki/File:Pushkin_Alexander_by_Sokolov_P..jpg',
                'descriptionshorturl' => 'https://commons.wikimedia.org/w/index.php?curid=3764973',
                'mime' => 'image/jpeg',
            ],
        ],
    ],
    17 => [
        'ns' => 6,
        'title' => 'Файл:Pushkin Alexander, self portret, 1820s.jpg',
        'missing' => true,
        'known' => true,
        'imagerepository' => 'shared',
        'imageinfo' => [
            0 => [
                'thumburl' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/Pushkin_Alexander%2C_self_portret%2C_1820s.jpg/261px-Pushkin_Alexander%2C_self_portret%2C_1820s.jpg',
                'thumbwidth' => 261,
                'thumbheight' => 300,
                'url' => 'https://upload.wikimedia.org/wikipedia/commons/0/00/Pushkin_Alexander%2C_self_portret%2C_1820s.jpg',
                'descriptionurl' => 'https://commons.wikimedia.org/wiki/File:Pushkin_Alexander,_self_portret,_1820s.jpg',
                'descriptionshorturl' => 'https://commons.wikimedia.org/w/index.php?curid=3753359',
                'mime' => 'image/jpeg',
            ],
        ],
    ],
    18 => [
        'ns' => 6,
        'title' => 'Файл:Pushkin Alexander, 1831 by Sokolov P..jpg',
        'missing' => true,
        'known' => true,
        'imagerepository' => 'shared',
        'imageinfo' => [
            0 => [
                'thumburl' => 'https://upload.wikimedia.org/wikipedia/commons/c/c8/Pushkin_Alexander%2C_1831_by_Sokolov_P..jpg',
                'thumbwidth' => 227,
                'thumbheight' => 300,
                'url' => 'https://upload.wikimedia.org/wikipedia/commons/c/c8/Pushkin_Alexander%2C_1831_by_Sokolov_P..jpg',
                'descriptionurl' => 'https://commons.wikimedia.org/wiki/File:Pushkin_Alexander,_1831_by_Sokolov_P..jpg',
                'descriptionshorturl' => 'https://commons.wikimedia.org/w/index.php?curid=3764792',
                'mime' => 'image/jpeg',
            ],
        ],
    ],
    19 => [
        'ns' => 6,
        'title' => 'Файл:Pushkin 04.jpg',
        'missing' => true,
        'known' => true,
        'imagerepository' => 'shared',
        'imageinfo' => [
            0 => [
                'thumburl' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/Pushkin_04.jpg/230px-Pushkin_04.jpg',
                'thumbwidth' => 230,
                'thumbheight' => 300,
                'url' => 'https://upload.wikimedia.org/wikipedia/commons/3/3f/Pushkin_04.jpg',
                'descriptionurl' => 'https://commons.wikimedia.org/wiki/File:Pushkin_04.jpg',
                'descriptionshorturl' => 'https://commons.wikimedia.org/w/index.php?curid=5977807',
                'mime' => 'image/jpeg',
            ],
        ],
    ],
    20 => [
        'ns' => 6,
        'title' => "Файл:Pushkin's duel with d'Anthes, atrist A. Naumov 1884.jpg",
        'missing' => true,
        'known' => true,
        'imagerepository' => 'shared',
        'imageinfo' => [
            0 => [
                'thumburl' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Pushkin%27s_duel_with_d%27Anthes%2C_atrist_A._Naumov_1884.jpg/300px-Pushkin%27s_duel_with_d%27Anthes%2C_atrist_A._Naumov_1884.jpg',
                'thumbwidth' => 300,
                'thumbheight' => 185,
                'url' => 'https://upload.wikimedia.org/wikipedia/commons/2/2e/Pushkin%27s_duel_with_d%27Anthes%2C_atrist_A._Naumov_1884.jpg',
                'descriptionurl' => 'https://commons.wikimedia.org/wiki/File:Pushkin%27s_duel_with_d%27Anthes,_atrist_A._Naumov_1884.jpg',
                'descriptionshorturl' => 'https://commons.wikimedia.org/w/index.php?curid=18158335',
                'mime' => 'image/jpeg',
            ],
        ],
    ],
    21 => [
        'ns' => 6,
        'title' => 'Файл:Portrait of Alexander Pushkin (Orest Kiprensky, 1827).PNG',
        'missing' => true,
        'known' => true,
        'imagerepository' => 'shared',
        'imageinfo' => [
            0 => [
                'thumburl' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/Portrait_of_Alexander_Pushkin_%28Orest_Kiprensky%2C_1827%29.PNG/257px-Portrait_of_Alexander_Pushkin_%28Orest_Kiprensky%2C_1827%29.PNG',
                'thumbwidth' => 257,
                'thumbheight' => 300,
                'url' => 'https://upload.wikimedia.org/wikipedia/commons/5/56/Portrait_of_Alexander_Pushkin_%28Orest_Kiprensky%2C_1827%29.PNG',
                'descriptionurl' => 'https://commons.wikimedia.org/wiki/File:Portrait_of_Alexander_Pushkin_(Orest_Kiprensky,_1827).PNG',
                'descriptionshorturl' => 'https://commons.wikimedia.org/w/index.php?curid=23633692',
                'mime' => 'image/png',
            ],
        ],
    ],
    22 => [
        'ns' => 6,
        'title' => 'Файл:Natalia Pushkina by Brullov.jpg',
        'missing' => true,
        'known' => true,
        'imagerepository' => 'shared',
        'imageinfo' => [
            0 => [
                'thumburl' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bd/Natalia_Pushkina_by_Brullov.jpg/241px-Natalia_Pushkina_by_Brullov.jpg',
                'thumbwidth' => 241,
                'thumbheight' => 300,
                'url' => 'https://upload.wikimedia.org/wikipedia/commons/b/bd/Natalia_Pushkina_by_Brullov.jpg',
                'descriptionurl' => 'https://commons.wikimedia.org/wiki/File:Natalia_Pushkina_by_Brullov.jpg',
                'descriptionshorturl' => 'https://commons.wikimedia.org/w/index.php?curid=653541',
                'mime' => 'image/jpeg',
            ],
        ],
    ],
    23 => [
        'ns' => 6,
        'title' => 'Файл:N.O.Puskina.jpg',
        'missing' => true,
        'known' => true,
        'imagerepository' => 'shared',
        'imageinfo' => [
            0 => [
                'thumburl' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2b/N.O.Puskina.jpg/264px-N.O.Puskina.jpg',
                'thumbwidth' => 264,
                'thumbheight' => 300,
                'url' => 'https://upload.wikimedia.org/wikipedia/commons/2/2b/N.O.Puskina.jpg',
                'descriptionurl' => 'https://commons.wikimedia.org/wiki/File:N.O.Puskina.jpg',
                'descriptionshorturl' => 'https://commons.wikimedia.org/w/index.php?curid=10185913',
                'mime' => 'image/jpeg',
            ],
        ],
    ],
    24 => [
        'ns' => 6,
        'title' => 'Файл:Fontanka Embamkment 185.jpg',
        'missing' => true,
        'known' => true,
        'imagerepository' => 'shared',
        'imageinfo' => [
            0 => [
                'thumburl' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ee/Fontanka_Embamkment_185.jpg/300px-Fontanka_Embamkment_185.jpg',
                'thumbwidth' => 300,
                'thumbheight' => 200,
                'url' => 'https://upload.wikimedia.org/wikipedia/commons/e/ee/Fontanka_Embamkment_185.jpg',
                'descriptionurl' => 'https://commons.wikimedia.org/wiki/File:Fontanka_Embamkment_185.jpg',
                'descriptionshorturl' => 'https://commons.wikimedia.org/w/index.php?curid=43398496',
                'mime' => 'image/jpeg',
            ],
        ],
    ],
    25 => [
        'ns' => 6,
        'title' => 'Файл:Flag of Russia.svg',
        'missing' => true,
        'known' => true,
        'imagerepository' => 'shared',
        'imageinfo' => [
            0 => [
                'thumburl' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Flag_of_Russia.svg/300px-Flag_of_Russia.svg.png',
                'thumbwidth' => 300,
                'thumbheight' => 200,
                'url' => 'https://upload.wikimedia.org/wikipedia/commons/f/f3/Flag_of_Russia.svg',
                'descriptionurl' => 'https://commons.wikimedia.org/wiki/File:Flag_of_Russia.svg',
                'descriptionshorturl' => 'https://commons.wikimedia.org/w/index.php?curid=9450374',
                'mime' => 'image/svg+xml',
            ],
        ],
    ],
    26 => [
        'ns' => 6,
        'title' => 'Файл:Emblem-important.svg',
        'missing' => true,
        'known' => true,
        'imagerepository' => 'shared',
        'imageinfo' => [
            0 => [
                'thumburl' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Emblem-important.svg/300px-Emblem-important.svg.png',
                'thumbwidth' => 300,
                'thumbheight' => 300,
                'url' => 'https://upload.wikimedia.org/wikipedia/commons/4/4c/Emblem-important.svg',
                'descriptionurl' => 'https://commons.wikimedia.org/wiki/File:Emblem-important.svg',
                'descriptionshorturl' => 'https://commons.wikimedia.org/w/index.php?curid=441963',
                'mime' => 'image/svg+xml',
            ],
        ],
    ],
    27 => [
        'ns' => 6,
        'title' => "Файл:Duel of Pushkin and d'Anthes (19th century).jpg",
        'missing' => true,
        'known' => true,
        'imagerepository' => 'shared',
        'imageinfo' => [
            0 => [
                'thumburl' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/Duel_of_Pushkin_and_d%27Anthes_%2819th_century%29.jpg/300px-Duel_of_Pushkin_and_d%27Anthes_%2819th_century%29.jpg',
                'thumbwidth' => 300,
                'thumbheight' => 218,
                'url' => 'https://upload.wikimedia.org/wikipedia/commons/7/7e/Duel_of_Pushkin_and_d%27Anthes_%2819th_century%29.jpg',
                'descriptionurl' => 'https://commons.wikimedia.org/wiki/File:Duel_of_Pushkin_and_d%27Anthes_(19th_century).jpg',
                'descriptionshorturl' => 'https://commons.wikimedia.org/w/index.php?curid=6926983',
                'mime' => 'image/jpeg',
            ],
        ],
    ],
    28 => [
        'ns' => 6,
        'title' => 'Файл:Commons-logo.svg',
        'missing' => true,
        'known' => true,
        'imagerepository' => 'shared',
        'imageinfo' => [
            0 => [
                'thumburl' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Commons-logo.svg/223px-Commons-logo.svg.png',
                'thumbwidth' => 223,
                'thumbheight' => 300,
                'url' => 'https://upload.wikimedia.org/wikipedia/commons/4/4a/Commons-logo.svg',
                'descriptionurl' => 'https://commons.wikimedia.org/wiki/File:Commons-logo.svg',
                'descriptionshorturl' => 'https://commons.wikimedia.org/w/index.php?curid=317966',
                'mime' => 'image/svg+xml',
            ],
        ],
    ],
    29 => [
        'ns' => 6,
        'title' => 'Файл:Arina Rodionovna.jpg',
        'missing' => true,
        'known' => true,
        'imagerepository' => 'shared',
        'imageinfo' => [
            0 => [
                'thumburl' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Arina_Rodionovna.jpg/236px-Arina_Rodionovna.jpg',
                'thumbwidth' => 236,
                'thumbheight' => 300,
                'url' => 'https://upload.wikimedia.org/wikipedia/commons/f/f6/Arina_Rodionovna.jpg',
                'descriptionurl' => 'https://commons.wikimedia.org/wiki/File:Arina_Rodionovna.jpg',
                'descriptionshorturl' => 'https://commons.wikimedia.org/w/index.php?curid=19073944',
                'mime' => 'image/jpeg',
            ],
        ],
    ],
    30 => [
        'ns' => 6,
        'title' => 'Файл:Aquote2.png',
        'missing' => true,
        'known' => true,
        'imagerepository' => 'shared',
        'imageinfo' => [
            0 => [
                'thumburl' => 'https://upload.wikimedia.org/wikipedia/commons/4/49/Aquote2.png',
                'thumbwidth' => 40,
                'thumbheight' => 30,
                'url' => 'https://upload.wikimedia.org/wikipedia/commons/4/49/Aquote2.png',
                'descriptionurl' => 'https://commons.wikimedia.org/wiki/File:Aquote2.png',
                'descriptionshorturl' => 'https://commons.wikimedia.org/w/index.php?curid=1247587',
                'mime' => 'image/png',
            ],
        ],
    ],
    31 => [
        'ns' => 6,
        'title' => 'Файл:Aquote1.png',
        'missing' => true,
        'known' => true,
        'imagerepository' => 'shared',
        'imageinfo' => [
            0 => [
                'thumburl' => 'https://upload.wikimedia.org/wikipedia/commons/4/44/Aquote1.png',
                'thumbwidth' => 40,
                'thumbheight' => 30,
                'url' => 'https://upload.wikimedia.org/wikipedia/commons/4/44/Aquote1.png',
                'descriptionurl' => 'https://commons.wikimedia.org/wiki/File:Aquote1.png',
                'descriptionshorturl' => 'https://commons.wikimedia.org/w/index.php?curid=1247581',
                'mime' => 'image/png',
            ],
        ],
    ],
    32 => [
        'ns' => 6,
        'title' => 'Файл:A.S.Pushkin.jpg',
        'missing' => true,
        'known' => true,
        'imagerepository' => 'shared',
        'imageinfo' => [
            0 => [
                'thumburl' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/ff/A.S.Pushkin.jpg/222px-A.S.Pushkin.jpg',
                'thumbwidth' => 222,
                'thumbheight' => 300,
                'url' => 'https://upload.wikimedia.org/wikipedia/commons/f/ff/A.S.Pushkin.jpg',
                'descriptionurl' => 'https://commons.wikimedia.org/wiki/File:A.S.Pushkin.jpg',
                'descriptionshorturl' => 'https://commons.wikimedia.org/w/index.php?curid=14207961',
                'mime' => 'image/jpeg',
            ],
        ],
    ],
    33 => [
        'pageid' => 921293,
        'ns' => 6,
        'title' => 'Файл:Pushkin rod.png',
        'imagerepository' => 'local',
        'imageinfo' => [
            0 => [
                'thumburl' => 'https://upload.wikimedia.org/wikipedia/ru/thumb/3/3f/Pushkin_rod.png/135px-Pushkin_rod.png',
                'thumbwidth' => 135,
                'thumbheight' => 300,
                'url' => 'https://upload.wikimedia.org/wikipedia/ru/3/3f/Pushkin_rod.png',
                'descriptionurl' => 'https://ru.wikipedia.org/wiki/%D0%A4%D0%B0%D0%B9%D0%BB:Pushkin_rod.png',
                'descriptionshorturl' => 'https://ru.wikipedia.org/w/index.php?curid=921293',
                'mime' => 'image/png',
            ],
        ],
    ],
    34 => [
        'ns' => 6,
        'title' => 'Файл:Main-Section-Image.jpg',
        'missing' => true,
        'known' => true,
        'imagerepository' => 'shared',
        'imageinfo' => [
            0 => [
                'thumburl' => 'http://via.placeholder.com/300x280',
                'thumbwidth' => 300,
                'thumbheight' => 280,
                'url' => 'http://via.placeholder.com/1000x1000',
                'descriptionurl' => 'https://commons.wikimedia.org/wiki/File:Main-Section-Image.jpg',
                'descriptionshorturl' => 'https://commons.wikimedia.org/w/index.php?curid=14207961',
                'mime' => 'image/jpeg',
            ],
        ],
    ],
    35 => [
        'ns' => 6,
        'title' => 'Файл:Another-Main-Section-Image.jpg',
        'missing' => true,
        'known' => true,
        'imagerepository' => 'shared',
        'imageinfo' => [
            0 => [
                'thumburl' => 'http://via.placeholder.com/300x280',
                'thumbwidth' => 300,
                'thumbheight' => 280,
                'url' => 'http://via.placeholder.com/1100x1100',
                'descriptionurl' => 'https://commons.wikimedia.org/wiki/File:Another-Main-Section-Image.jpg',
                'descriptionshorturl' => 'https://commons.wikimedia.org/w/index.php?curid=14207961',
                'mime' => 'image/jpeg',
            ],
        ],
    ],
    36 => [
        'ns' => 6,
        'title' => 'Файл:Mikhail Andreyevich Dostoyevsky.jpg',
        'missing' => true,
        'known' => true,
        'imagerepository' => 'shared',
        'imageinfo' => [
            0 => [
                'thumburl' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/aa/Mikhail_Andreyevich_Dostoyevsky.jpg/188px-Mikhail_Andreyevich_Dostoyevsky.jpg',
                'thumbwidth' => 188,
                'thumbheight' => 250,
                'url' => 'https://upload.wikimedia.org/wikipedia/commons/a/aa/Mikhail_Andreyevich_Dostoyevsky.jpg',
                'descriptionurl' => 'https://commons.wikimedia.org/wiki/File:Mikhail_Andreyevich_Dostoyevsky.jpg',
                'descriptionshorturl' => 'https://commons.wikimedia.org/w/index.php?curid=25997411',
                'mime' => 'image/jpeg',
            ],
        ],
    ],
    37 => [
        'ns' => 6,
        'title' => 'Файл:Maria Fyodorovna Dostoyevskaya.jpg',
        'missing' => true,
        'known' => true,
        'imagerepository' => 'shared',
        'imageinfo' => [
            0 => [
                'thumburl' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Maria_Fyodorovna_Dostoyevskaya.jpg/189px-Maria_Fyodorovna_Dostoyevskaya.jpg',
                'thumbwidth' => 189,
                'thumbheight' => 250,
                'url' => 'https://upload.wikimedia.org/wikipedia/commons/1/19/Maria_Fyodorovna_Dostoyevskaya.jpg',
                'descriptionurl' => 'https://commons.wikimedia.org/wiki/File:Maria_Fyodorovna_Dostoyevskaya.jpg',
                'descriptionshorturl' => 'https://commons.wikimedia.org/w/index.php?curid=25997380',
                'mime' => 'image/jpeg',
            ],
        ],
    ],
    38 => [
        'ns' => 6,
        'title' => 'Файл:Gallery-Image-1.jpg',
        'missing' => true,
        'known' => true,
        'imagerepository' => 'shared',
        'imageinfo' => [
            0 => [
                'thumburl' => 'http://via.placeholder.com/300x280',
                'thumbwidth' => 300,
                'thumbheight' => 280,
                'url' => 'http://via.placeholder.com/1001x1001',
                'descriptionurl' => 'https://commons.wikimedia.org/wiki/File:Gallery-Image-1.jpg',
                'descriptionshorturl' => 'https://commons.wikimedia.org/w/index.php?curid=14207961',
                'mime' => 'image/jpeg',
            ],
        ],
    ],
    39 => [
        'ns' => 6,
        'title' => 'Файл:Gallery-Image-2.jpg',
        'missing' => true,
        'known' => true,
        'imagerepository' => 'shared',
        'imageinfo' => [
            0 => [
                'thumburl' => 'http://via.placeholder.com/300x280',
                'thumbwidth' => 300,
                'thumbheight' => 280,
                'url' => 'http://via.placeholder.com/1002x1002',
                'descriptionurl' => 'https://commons.wikimedia.org/wiki/File:Gallery-Image-2.jpg',
                'descriptionshorturl' => 'https://commons.wikimedia.org/w/index.php?curid=14207961',
                'mime' => 'image/jpeg',
            ],
        ],
    ],
    40 => [
        'ns' => 6,
        'title' => 'Файл:Gallery-Image-3.jpg',
        'missing' => true,
        'known' => true,
        'imagerepository' => 'shared',
        'imageinfo' => [
            0 => [
                'thumburl' => 'http://via.placeholder.com/300x280',
                'thumbwidth' => 300,
                'thumbheight' => 280,
                'url' => 'http://via.placeholder.com/1003x1003',
                'descriptionurl' => 'https://commons.wikimedia.org/wiki/File:Gallery-Image-3.jpg',
                'descriptionshorturl' => 'https://commons.wikimedia.org/w/index.php?curid=14207961',
                'mime' => 'image/jpeg',
            ],
        ],
    ],
    41 => [
        'ns' => 6,
        'title' => 'Файл:Gallery-Image-4.jpg',
        'missing' => true,
        'known' => true,
        'imagerepository' => 'shared',
        'imageinfo' => [
            0 => [
                'thumburl' => 'http://via.placeholder.com/300x280',
                'thumbwidth' => 300,
                'thumbheight' => 280,
                'url' => 'http://via.placeholder.com/1004x1004',
                'descriptionurl' => 'https://commons.wikimedia.org/wiki/File:Gallery-Image-4.jpg',
                'descriptionshorturl' => 'https://commons.wikimedia.org/w/index.php?curid=14207961',
                'mime' => 'image/jpeg',
            ],
        ],
    ],
    42 => [
        'ns' => 6,
        'title' => 'Файл:GrayTable-1.jpg',
        'missing' => true,
        'known' => true,
        'imagerepository' => 'shared',
        'imageinfo' => [
            0 => [
                'thumburl' => 'http://via.placeholder.com/300x280',
                'thumbwidth' => 300,
                'thumbheight' => 280,
                'url' => 'http://via.placeholder.com/1005x1005',
                'descriptionurl' => 'https://commons.wikimedia.org/wiki/File:GrayTable-1.jpg',
                'descriptionshorturl' => 'https://commons.wikimedia.org/w/index.php?curid=14207961',
                'mime' => 'image/jpeg',
            ],
        ],
    ],
    43 => [
        'ns' => 6,
        'title' => 'Файл:GrayTable-2.jpg',
        'missing' => true,
        'known' => true,
        'imagerepository' => 'shared',
        'imageinfo' => [
            0 => [
                'thumburl' => 'http://via.placeholder.com/300x280',
                'thumbwidth' => 300,
                'thumbheight' => 280,
                'url' => 'http://via.placeholder.com/1006x1006',
                'descriptionurl' => 'https://commons.wikimedia.org/wiki/File:GrayTable-2.jpg',
                'descriptionshorturl' => 'https://commons.wikimedia.org/w/index.php?curid=14207961',
                'mime' => 'image/jpeg',
            ],
        ],
    ],
    44 => [
        'ns' => 6,
        'title' => 'Файл:GrayTable-3.jpg',
        'missing' => true,
        'known' => true,
        'imagerepository' => 'shared',
        'imageinfo' => [
            0 => [
                'thumburl' => 'http://via.placeholder.com/300x280',
                'thumbwidth' => 300,
                'thumbheight' => 280,
                'url' => 'http://via.placeholder.com/1007x1007',
                'descriptionurl' => 'https://commons.wikimedia.org/wiki/File:GrayTable-3.jpg',
                'descriptionshorturl' => 'https://commons.wikimedia.org/w/index.php?curid=14207961',
                'mime' => 'image/jpeg',
            ],
        ],
    ],
    45 => [
        'ns' => 6,
        'title' => 'Файл:GrayTable-4.jpg',
        'missing' => true,
        'known' => true,
        'imagerepository' => 'shared',
        'imageinfo' => [
            0 => [
                'thumburl' => 'http://via.placeholder.com/300x280',
                'thumbwidth' => 300,
                'thumbheight' => 280,
                'url' => 'http://via.placeholder.com/1008x1008',
                'descriptionurl' => 'https://commons.wikimedia.org/wiki/File:GrayTable-4.jpg',
                'descriptionshorturl' => 'https://commons.wikimedia.org/w/index.php?curid=14207961',
                'mime' => 'image/jpeg',
            ],
        ],
    ],
    46 => [
        'ns' => 6,
        'title' => 'Файл:Photo-Column-1.jpg',
        'missing' => true,
        'known' => true,
        'imagerepository' => 'shared',
        'imageinfo' => [
            0 => [
                'thumburl' => 'http://via.placeholder.com/300x280',
                'thumbwidth' => 300,
                'thumbheight' => 280,
                'url' => 'http://via.placeholder.com/1010x1010',
                'descriptionurl' => 'https://commons.wikimedia.org/wiki/File:Photo-Column-1.jpg',
                'descriptionshorturl' => 'https://commons.wikimedia.org/w/index.php?curid=14207961',
                'mime' => 'image/jpeg',
            ],
        ],
    ],
    47 => [
        'ns' => 6,
        'title' => 'Файл:Photo-Column-2.jpg',
        'missing' => true,
        'known' => true,
        'imagerepository' => 'shared',
        'imageinfo' => [
            0 => [
                'thumburl' => 'http://via.placeholder.com/300x280',
                'thumbwidth' => 300,
                'thumbheight' => 280,
                'url' => 'http://via.placeholder.com/1011x1011',
                'descriptionurl' => 'https://commons.wikimedia.org/wiki/File:Photo-Column-2.jpg',
                'descriptionshorturl' => 'https://commons.wikimedia.org/w/index.php?curid=14207961',
                'mime' => 'image/jpeg',
            ],
        ],
    ],
    48 => [
        'ns' => 6,
        'title' => 'Файл:Photo-Column-3.jpg',
        'missing' => true,
        'known' => true,
        'imagerepository' => 'shared',
        'imageinfo' => [
            0 => [
                'thumburl' => 'http://via.placeholder.com/300x280',
                'thumbwidth' => 300,
                'thumbheight' => 280,
                'url' => 'http://via.placeholder.com/1012x1012',
                'descriptionurl' => 'https://commons.wikimedia.org/wiki/File:Photo-Column-3.jpg',
                'descriptionshorturl' => 'https://commons.wikimedia.org/w/index.php?curid=14207961',
                'mime' => 'image/jpeg',
            ],
        ],
    ],
    49 => [
        'ns' => 6,
        'title' => 'Файл:Photo-Column-4.jpg',
        'missing' => true,
        'known' => true,
        'imagerepository' => 'shared',
        'imageinfo' => [
            0 => [
                'thumburl' => 'http://via.placeholder.com/300x280',
                'thumbwidth' => 300,
                'thumbheight' => 280,
                'url' => 'http://via.placeholder.com/1013x1013',
                'descriptionurl' => 'https://commons.wikimedia.org/wiki/File:Photo-Column-4.jpg',
                'descriptionshorturl' => 'https://commons.wikimedia.org/w/index.php?curid=14207961',
                'mime' => 'image/jpeg',
            ],
        ],
    ],
    50 => [
        'ns' => 6,
        'title' => 'Файл:File with spaces here and underscores in wikitext.jpg',
        'missing' => true,
        'known' => true,
        'imagerepository' => 'shared',
        'imageinfo' => [
            0 => [
                'thumburl' => 'http://via.placeholder.com/300x280',
                'thumbwidth' => 300,
                'thumbheight' => 280,
                'url' => 'http://via.placeholder.com/1020x1020',
                'descriptionurl' => 'https://commons.wikimedia.org/wiki/File:File with spaces here and underscores in wikitext.jpg',
                'descriptionshorturl' => 'https://commons.wikimedia.org/w/index.php?curid=14207961',
                'mime' => 'image/jpeg',
            ],
        ],
    ],
    51 => [
        'ns' => 6,
        'title' => 'Файл:File_with_underscores_here_and_spaces_in_wikitext.jpg',
        'missing' => true,
        'known' => true,
        'imagerepository' => 'shared',
        'imageinfo' => [
            0 => [
                'thumburl' => 'http://via.placeholder.com/300x280',
                'thumbwidth' => 300,
                'thumbheight' => 280,
                'url' => 'http://via.placeholder.com/1021x1021',
                'descriptionurl' => 'https://commons.wikimedia.org/wiki/File:File_with_underscores_here_and_spaces_in_wikitext.jpg',
                'descriptionshorturl' => 'https://commons.wikimedia.org/w/index.php?curid=14207961',
                'mime' => 'image/jpeg',
            ],
        ],
    ],
    52 => [
        'ns' => 6,
        'title' => 'Файл:Filipp Kirkorov voice.oga',
        'missing' => true,
        'known' => true,
        'imagerepository' => 'shared',
        'imageinfo' => [
            0 => [
                'thumburl' => 'https://ru.wikipedia.org/w/resources/assets/file-type-icons/fileicon-ogg.png',
                'thumbwidth' => 250,
                'thumbheight' => 250,
                'url' => 'https://upload.wikimedia.org/wikipedia/commons/2/26/Filipp_Kirkorov_voice.oga',
                'descriptionurl' => 'https://commons.wikimedia.org/wiki/File:Filipp_Kirkorov_voice.oga',
                'descriptionshorturl' => 'https://commons.wikimedia.org/w/index.php?curid=39545292',
                'mime' => 'application/ogg',
            ],
        ],
    ],
    53 => [
        'ns' => 6,
        'title' => 'Файл:Филипп Киркоров - Атлантида.oga',
        'missing' => true,
        'known' => true,
        'imagerepository' => 'shared',
        'imageinfo' => [
            0 => [
                'thumburl' => 'https://ru.wikipedia.org/w/resources/assets/file-type-icons/fileicon-ogg.png',
                'thumbwidth' => 250,
                'thumbheight' => 250,
                'url' => 'https://upload.wikimedia.org/wikipedia/commons/2/26/Филипп_Киркоров_-_Атлантида.oga',
                'descriptionurl' => 'https://commons.wikimedia.org/wiki/File:Филипп_Киркоров_-_Атлантида.oga',
                'descriptionshorturl' => 'https://commons.wikimedia.org/w/index.php?curid=39545292',
                'mime' => 'application/ogg',
            ],
        ],
    ],
    54 => [
        'ns' => 6,
        'title' => 'Файл:Madonna-lucky star.ogg',
        'missing' => true,
        'known' => true,
        'imagerepository' => 'shared',
        'imageinfo' => [
            0 => [
                'thumburl' => 'https://ru.wikipedia.org/w/resources/assets/file-type-icons/fileicon-ogg.png',
                'thumbwidth' => 250,
                'thumbheight' => 250,
                'url' => 'https://upload.wikimedia.org/wikipedia/commons/2/26/Madonna-lucky star.ogg',
                'descriptionurl' => 'https://commons.wikimedia.org/wiki/File:Madonna-lucky star.ogg',
                'descriptionshorturl' => 'https://commons.wikimedia.org/w/index.php?curid=39545292',
                'mime' => 'application/ogg',
            ],
        ],
    ],
    55 => [
        'ns' => 6,
        'title' => 'Файл:De-Ludwig_van_Beethoven.ogg',
        'missing' => true,
        'known' => true,
        'imagerepository' => 'shared',
        'imageinfo' => [
            0 => [
                'thumburl' => 'https://ru.wikipedia.org/w/resources/assets/file-type-icons/fileicon-ogg.png',
                'thumbwidth' => 250,
                'thumbheight' => 250,
                'url' => 'https://upload.wikimedia.org/wikipedia/commons/2/26/De-Ludwig_van_Beethoven.ogg',
                'descriptionurl' => 'https://commons.wikimedia.org/wiki/File:De-Ludwig_van_Beethoven.ogg',
                'descriptionshorturl' => 'https://commons.wikimedia.org/w/index.php?curid=39545292',
                'mime' => 'application/ogg',
            ],
        ],
    ],
    56 => [
        'ns' => 6,
        'title' => 'Файл:Multiple-Image-1.jpg',
        'missing' => true,
        'known' => true,
        'imagerepository' => 'shared',
        'imageinfo' => [
            0 => [
                'thumburl' => 'http://via.placeholder.com/300x280',
                'thumbwidth' => 300,
                'thumbheight' => 280,
                'url' => 'http://via.placeholder.com/1020x1020',
                'descriptionurl' => 'https://commons.wikimedia.org/wiki/File:Multiple-Image-1.jpg',
                'descriptionshorturl' => 'https://commons.wikimedia.org/w/index.php?curid=14207961',
                'mime' => 'image/jpeg',
            ],
        ],
    ],
    57 => [
        'ns' => 6,
        'title' => 'Файл:Multiple-Image-2.jpg',
        'missing' => true,
        'known' => true,
        'imagerepository' => 'shared',
        'imageinfo' => [
            0 => [
                'thumburl' => 'http://via.placeholder.com/300x280',
                'thumbwidth' => 300,
                'thumbheight' => 280,
                'url' => 'http://via.placeholder.com/1021x1021',
                'descriptionurl' => 'https://commons.wikimedia.org/wiki/File:Multiple-Image-2.jpg',
                'descriptionshorturl' => 'https://commons.wikimedia.org/w/index.php?curid=14207961',
                'mime' => 'image/jpeg',
            ],
        ],
    ],
    58 => [
        'ns' => 6,
        'title' => 'Файл:Multiple-Image-3.jpg',
        'missing' => true,
        'known' => true,
        'imagerepository' => 'shared',
        'imageinfo' => [
            0 => [
                'thumburl' => 'http://via.placeholder.com/300x280',
                'thumbwidth' => 300,
                'thumbheight' => 280,
                'url' => 'http://via.placeholder.com/1022x1022',
                'descriptionurl' => 'https://commons.wikimedia.org/wiki/File:Multiple-Image-3.jpg',
                'descriptionshorturl' => 'https://commons.wikimedia.org/w/index.php?curid=14207961',
                'mime' => 'image/jpeg',
            ],
        ],
    ],
    59 => [
        'ns' => 6,
        'title' => 'Файл:Multiple-Image-Ru-1.jpg',
        'missing' => true,
        'known' => true,
        'imagerepository' => 'shared',
        'imageinfo' => [
            0 => [
                'thumburl' => 'http://via.placeholder.com/300x280',
                'thumbwidth' => 300,
                'thumbheight' => 280,
                'url' => 'http://via.placeholder.com/1030x1030',
                'descriptionurl' => 'https://commons.wikimedia.org/wiki/File:Multiple-Image-Ru-1.jpg',
                'descriptionshorturl' => 'https://commons.wikimedia.org/w/index.php?curid=14207961',
                'mime' => 'image/jpeg',
            ],
        ],
    ],
    60 => [
        'ns' => 6,
        'title' => 'Файл:Multiple-Image-Ru-2.jpg',
        'missing' => true,
        'known' => true,
        'imagerepository' => 'shared',
        'imageinfo' => [
            0 => [
                'thumburl' => 'http://via.placeholder.com/300x280',
                'thumbwidth' => 300,
                'thumbheight' => 280,
                'url' => 'http://via.placeholder.com/1031x1031',
                'descriptionurl' => 'https://commons.wikimedia.org/wiki/File:Multiple-Image-Ru-2.jpg',
                'descriptionshorturl' => 'https://commons.wikimedia.org/w/index.php?curid=14207961',
                'mime' => 'image/jpeg',
            ],
        ],
    ],
    61 => [
        'ns' => 6,
        'title' => 'Файл:Multiple-Image-Ru-3.jpg',
        'missing' => true,
        'known' => true,
        'imagerepository' => 'shared',
        'imageinfo' => [
            0 => [
                'thumburl' => 'http://via.placeholder.com/300x280',
                'thumbwidth' => 300,
                'thumbheight' => 280,
                'url' => 'http://via.placeholder.com/1032x1032',
                'descriptionurl' => 'https://commons.wikimedia.org/wiki/File:Multiple-Image-Ru-3.jpg',
                'descriptionshorturl' => 'https://commons.wikimedia.org/w/index.php?curid=14207961',
                'mime' => 'image/jpeg',
            ],
        ],
    ],
    62 => [
        'ns' => 6,
        'title' => 'Файл:Listen-01.ogg',
        'missing' => true,
        'known' => true,
        'imagerepository' => 'shared',
        'imageinfo' => [
            0 => [
                'thumburl' => 'http://via.placeholder.com/300x280',
                'thumbwidth' => 300,
                'thumbheight' => 280,
                'url' => 'http://via.placeholder.com/1040x1040',
                'descriptionurl' => 'https://commons.wikimedia.org/wiki/File:Listen-01.ogg',
                'descriptionshorturl' => 'https://commons.wikimedia.org/w/index.php?curid=14207961',
                'mime' => 'image/jpeg',
            ],
        ],
    ],
    63 => [
        'ns' => 6,
        'title' => 'Файл:Listen-02.ogg',
        'missing' => true,
        'known' => true,
        'imagerepository' => 'shared',
        'imageinfo' => [
            0 => [
                'thumburl' => 'http://via.placeholder.com/300x280',
                'thumbwidth' => 300,
                'thumbheight' => 280,
                'url' => 'http://via.placeholder.com/1041x1041',
                'descriptionurl' => 'https://commons.wikimedia.org/wiki/File:Listen-02.ogg',
                'descriptionshorturl' => 'https://commons.wikimedia.org/w/index.php?curid=14207961',
                'mime' => 'image/jpeg',
            ],
        ],
    ],
    64 => [
        'ns' => 6,
        'title' => 'Файл:Listen-03.ogg',
        'missing' => true,
        'known' => true,
        'imagerepository' => 'shared',
        'imageinfo' => [
            0 => [
                'thumburl' => 'http://via.placeholder.com/300x280',
                'thumbwidth' => 300,
                'thumbheight' => 280,
                'url' => 'http://via.placeholder.com/1042x1042',
                'descriptionurl' => 'https://commons.wikimedia.org/wiki/File:Listen-03.ogg',
                'descriptionshorturl' => 'https://commons.wikimedia.org/w/index.php?curid=14207961',
                'mime' => 'image/jpeg',
            ],
        ],
    ],
    65 => [
        'ns' => 6,
        'title' => 'Файл:Nl-be_guy_verhofstadt.ogg',
        'missing' => true,
        'known' => true,
        'imagerepository' => 'shared',
        'imageinfo' => [
            0 => [
                'thumburl' => 'https://ru.wikipedia.org/w/resources/assets/file-type-icons/fileicon-ogg.png',
                'thumbwidth' => 250,
                'thumbheight' => 250,
                'url' => 'https://upload.wikimedia.org/wikipedia/commons/2/26/Nl-be_guy_verhofstadt.ogg',
                'descriptionurl' => 'https://commons.wikimedia.org/wiki/File:Nl-be_guy_verhofstadt.ogg',
                'descriptionshorturl' => 'https://commons.wikimedia.org/w/index.php?curid=39545292',
                'mime' => 'application/ogg',
            ],
        ],
    ],
    66 => [
        'ns' => 6,
        'title' => 'Файл:Audio-Gallery-1.ogg',
        'missing' => true,
        'known' => true,
        'imagerepository' => 'shared',
        'imageinfo' => [
            0 => [
                'thumburl' => 'https://ru.wikipedia.org/w/resources/assets/file-type-icons/fileicon-ogg.png',
                'thumbwidth' => 250,
                'thumbheight' => 250,
                'url' => 'https://upload.wikimedia.org/wikipedia/commons/2/26/Audio-Gallery-1.ogg',
                'descriptionurl' => 'https://commons.wikimedia.org/wiki/File:Audio-Gallery-1.ogg',
                'descriptionshorturl' => 'https://commons.wikimedia.org/w/index.php?curid=14207961',
                'mime' => 'application/ogg',
            ],
        ],
    ],
    67 => [
        'ns' => 6,
        'title' => 'Файл:Audio-Gallery-2.ogg',
        'missing' => true,
        'known' => true,
        'imagerepository' => 'shared',
        'imageinfo' => [
            0 => [
                'thumburl' => 'https://ru.wikipedia.org/w/resources/assets/file-type-icons/fileicon-ogg.png',
                'thumbwidth' => 250,
                'thumbheight' => 250,
                'url' => 'https://upload.wikimedia.org/wikipedia/commons/2/26/Audio-Gallery-2.ogg',
                'descriptionurl' => 'https://commons.wikimedia.org/wiki/File:Audio-Gallery-2.ogg',
                'descriptionshorturl' => 'https://commons.wikimedia.org/w/index.php?curid=14207961',
                'mime' => 'application/ogg',
            ],
        ],
    ],
    68 => [
        'ns' => 6,
        'title' => 'Файл:Audio-Gallery-3.ogg',
        'missing' => true,
        'known' => true,
        'imagerepository' => 'shared',
        'imageinfo' => [
            0 => [
                'thumburl' => 'https://ru.wikipedia.org/w/resources/assets/file-type-icons/fileicon-ogg.png',
                'thumbwidth' => 250,
                'thumbheight' => 250,
                'url' => 'https://upload.wikimedia.org/wikipedia/commons/2/26/Audio-Gallery-3.ogg',
                'descriptionurl' => 'https://commons.wikimedia.org/wiki/File:Audio-Gallery-3.ogg',
                'descriptionshorturl' => 'https://commons.wikimedia.org/w/index.php?curid=14207961',
                'mime' => 'application/ogg',
            ],
        ],
    ],
    69 => [
        'ns' => 6,
        'title' => 'Файл:Audio-Gallery-4.ogg',
        'missing' => true,
        'known' => true,
        'imagerepository' => 'shared',
        'imageinfo' => [
            0 => [
                'thumburl' => 'https://ru.wikipedia.org/w/resources/assets/file-type-icons/fileicon-ogg.png',
                'thumbwidth' => 250,
                'thumbheight' => 250,
                'url' => 'https://upload.wikimedia.org/wikipedia/commons/2/26/Audio-Gallery-4.ogg',
                'descriptionurl' => 'https://commons.wikimedia.org/wiki/File:Audio-Gallery-4.ogg',
                'descriptionshorturl' => 'https://commons.wikimedia.org/w/index.php?curid=14207961',
                'mime' => 'application/ogg',
            ],
        ],
    ],
    70 => [
        'ns' => 6,
        'title' => 'Файл:Audio-Gallery-5.wav',
        'missing' => true,
        'known' => true,
        'imagerepository' => 'shared',
        'imageinfo' => [
            0 => [
                'thumburl' => 'https://ru.wikipedia.org/w/resources/assets/file-type-icons/fileicon-ogg.png',
                'thumbwidth' => 250,
                'thumbheight' => 250,
                'url' => 'https://upload.wikimedia.org/wikipedia/commons/2/26/Audio-Gallery-5.wav',
                'descriptionurl' => 'https://commons.wikimedia.org/wiki/File:Audio-Gallery-5.wav',
                'descriptionshorturl' => 'https://commons.wikimedia.org/w/index.php?curid=14207961',
                'mime' => 'application/ogg',
            ],
        ],
    ],
    71 => [
        'ns' => 6,
        'title' => 'File:President Trump Gives a Statement on the Infrastructure Discussion.webm',
        'missing' => '',
        'known' => '',
        'imagerepository' => 'shared',
        'imageinfo' => [
            0 => [
                'thumburl' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/President_Trump_Gives_a_Statement_on_the_Infrastructure_Discussion.webm/300px--President_Trump_Gives_a_Statement_on_the_Infrastructure_Discussion.webm.jpg',
                'thumbwidth' => 300,
                'thumbheight' => 169,
                'url' => 'https://upload.wikimedia.org/wikipedia/commons/1/14/President_Trump_Gives_a_Statement_on_the_Infrastructure_Discussion.webm',
                'descriptionurl' => 'https://commons.wikimedia.org/wiki/File:President_Trump_Gives_a_Statement_on_the_Infrastructure_Discussion.webm',
                'descriptionshorturl' => 'https://commons.wikimedia.org/w/index.php?curid=61708081',
                'mime' => 'video/webm',
            ],
        ],
    ],
    72 => [
        'ns' => 6,
        'title' => 'File:Video-Gallery-1.webm',
        'missing' => '',
        'known' => '',
        'imagerepository' => 'shared',
        'imageinfo' => [
            0 => [
                'thumburl' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/Video-Gallery-1.webm/Video-Gallery-1.webm.jpg',
                'thumbwidth' => 300,
                'thumbheight' => 169,
                'url' => 'https://upload.wikimedia.org/wikipedia/commons/1/14/Video-Gallery-1.webm',
                'descriptionurl' => 'https://commons.wikimedia.org/wiki/File:Video-Gallery-1.webm',
                'descriptionshorturl' => 'https://commons.wikimedia.org/w/index.php?curid=61708081',
                'mime' => 'video/webm',
            ],
        ],
    ],
    73 => [
        'ns' => 6,
        'title' => 'File:Video-Gallery-2.webm',
        'missing' => '',
        'known' => '',
        'imagerepository' => 'shared',
        'imageinfo' => [
            0 => [
                'thumburl' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/Video-Gallery-2.webm/Video-Gallery-2.webm.jpg',
                'thumbwidth' => 300,
                'thumbheight' => 169,
                'url' => 'https://upload.wikimedia.org/wikipedia/commons/1/14/Video-Gallery-2.webm',
                'descriptionurl' => 'https://commons.wikimedia.org/wiki/File:Video-Gallery-2.webm',
                'descriptionshorturl' => 'https://commons.wikimedia.org/w/index.php?curid=61708081',
                'mime' => 'video/webm',
            ],
        ],
    ],
    74 => [
        'ns' => 6,
        'title' => 'File:Video-Gallery-3.webm',
        'missing' => '',
        'known' => '',
        'imagerepository' => 'shared',
        'imageinfo' => [
            0 => [
                'thumburl' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/Video-Gallery-3.webm/Video-Gallery-3.webm.jpg',
                'thumbwidth' => 300,
                'thumbheight' => 169,
                'url' => 'https://upload.wikimedia.org/wikipedia/commons/1/14/Video-Gallery-3.webm',
                'descriptionurl' => 'https://commons.wikimedia.org/wiki/File:Video-Gallery-3.webm',
                'descriptionshorturl' => 'https://commons.wikimedia.org/w/index.php?curid=61708081',
                'mime' => 'video/webm',
            ],
        ],
    ],
    75 => [
        'ns' => 6,
        'title' => 'File:Video-Gallery-4.webm',
        'missing' => '',
        'known' => '',
        'imagerepository' => 'shared',
        'imageinfo' => [
            0 => [
                'thumburl' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/Video-Gallery-4.webm/Video-Gallery-4.webm.jpg',
                'thumbwidth' => 300,
                'thumbheight' => 169,
                'url' => 'https://upload.wikimedia.org/wikipedia/commons/1/14/Video-Gallery-4.webm',
                'descriptionurl' => 'https://commons.wikimedia.org/wiki/File:Video-Gallery-4.webm',
                'descriptionshorturl' => 'https://commons.wikimedia.org/w/index.php?curid=61708081',
                'mime' => 'video/webm',
            ],
        ],
    ],
    76 => [
        'ns' => 6,
        'title' => 'File:Video-Gallery-5.webm',
        'missing' => '',
        'known' => '',
        'imagerepository' => 'shared',
        'imageinfo' => [
            0 => [
                'thumburl' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/Video-Gallery-5.webm/Video-Gallery-5.webm.jpg',
                'thumbwidth' => 300,
                'thumbheight' => 169,
                'url' => 'https://upload.wikimedia.org/wikipedia/commons/1/14/Video-Gallery-5.webm',
                'descriptionurl' => 'https://commons.wikimedia.org/wiki/File:Video-Gallery-5.webm',
                'descriptionshorturl' => 'https://commons.wikimedia.org/w/index.php?curid=61708081',
                'mime' => 'video/webm',
            ],
        ],
    ],
    77 => [
        'ns' => 6,
        'title' => 'Файл:Автограф Юрия Куклачёва.jpg',
        'missing' => true,
        'known' => true,
        'imagerepository' => 'shared',
        'imageinfo' => [
            0 => [
                'thumburl' => 'http://via.placeholder.com/300x280',
                'thumbwidth' => 300,
                'thumbheight' => 280,
                'url' => 'http://via.placeholder.com/1077x1077',
                'descriptionurl' => 'https://commons.wikimedia.org/wiki/Файл:Автограф Юрия Куклачёва.jpg',
                'descriptionshorturl' => 'https://commons.wikimedia.org/w/index.php?curid=14207961',
                'mime' => 'image/jpeg',
            ],
        ],
    ],
    78 => [
        'ns' => 6,
        'title' => 'Файл:George W Bush approval ratings.svg',
        'missing' => true,
        'known' => true,
        'imagerepository' => 'shared',
        'imageinfo' => [
            0 => [
                'thumburl' => 'http://via.placeholder.com/Thumb George W Bush approval ratings.svg',
                'thumbwidth' => 300,
                'thumbheight' => 280,
                'url' => 'http://via.placeholder.com/George W Bush approval ratings.svg',
                'descriptionurl' => 'https://commons.wikimedia.org/wiki/Файл:George W Bush approval ratings.svg',
                'descriptionshorturl' => 'https://commons.wikimedia.org/w/index.php?curid=14207961',
                'mime' => 'image/svg',
            ],
        ],
    ],
    79 => [
        'ns' => 6,
        'title' => 'Файл:CHopin SIgnature.svg',
        'missing' => true,
        'known' => true,
        'imagerepository' => 'shared',
        'imageinfo' => [
            0 => [
                'thumburl' => 'http://via.placeholder.com/300x280',
                'thumbwidth' => 300,
                'thumbheight' => 280,
                'url' => 'http://via.placeholder.com/CHopin SIgnature.svg',
                'descriptionurl' => 'https://commons.wikimedia.org/wiki/Файл:CHopin SIgnature.svg',
                'descriptionshorturl' => 'https://commons.wikimedia.org/w/index.php?curid=14207961',
                'mime' => 'image/svg',
            ],
        ],
    ],
    80 => [
        'ns' => 6,
        'title' => 'Файл:Frederic Chopin photo.jpeg',
        'missing' => true,
        'known' => true,
        'imagerepository' => 'shared',
        'imageinfo' => [
            0 => [
                'thumburl' => 'http://via.placeholder.com/300x280',
                'thumbwidth' => 300,
                'thumbheight' => 280,
                'url' => 'http://via.placeholder.com/Frederic Chopin photo.jpeg',
                'descriptionurl' => 'https://commons.wikimedia.org/wiki/Файл:Frederic Chopin photo.jpeg',
                'descriptionshorturl' => 'https://commons.wikimedia.org/w/index.php?curid=14207961',
                'mime' => 'image/jpg',
            ],
        ],
    ],
];
